# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [2]:
import numpy as np
import copy

**1.** Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
massiv = np.random.uniform(0,20,(4,7))
massiv 

array([[18.95498374, 14.08752753,  8.29790792, 12.58731632, 13.02556296,
        12.90407125,  5.90667366],
       [18.52738619,  2.13667669,  2.60500912, 14.72884112, 17.64945865,
        17.88084935, 17.22954722],
       [ 2.74428729, 19.16274051,  4.85502508, 13.2111938 , 11.65621133,
         4.62691026,  9.01490725],
       [12.12619771,  7.1113922 , 12.81638278, 10.25859263, 18.820141  ,
         3.05756078, 10.79715781]])

In [4]:
(massiv - massiv.min())/(massiv.max() - massiv.min())

array([[0.98779772, 0.70191507, 0.36187056, 0.61380245, 0.6395422 ,
        0.63240657, 0.22142505],
       [0.96268343, 0.        , 0.02750679, 0.73958165, 0.91111969,
        0.92471007, 0.88645683],
       [0.03568709, 1.        , 0.15965806, 0.65044494, 0.55911541,
        0.14626009, 0.40398243],
       [0.58671935, 0.29218236, 0.62725632, 0.4770284 , 0.97987794,
        0.05408673, 0.50866021]])

**2.** Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [5]:
arr = np.random.randint(0,10,(8,10))
arr

array([[7, 6, 8, 0, 6, 5, 6, 5, 5, 2],
       [4, 0, 6, 3, 1, 7, 1, 0, 6, 2],
       [4, 8, 4, 1, 6, 6, 4, 0, 7, 3],
       [8, 1, 2, 8, 4, 6, 2, 3, 7, 9],
       [9, 1, 4, 8, 5, 3, 0, 8, 4, 8],
       [8, 5, 6, 1, 0, 6, 7, 1, 9, 6],
       [1, 5, 0, 5, 6, 5, 9, 7, 7, 1],
       [3, 6, 1, 3, 0, 7, 3, 0, 1, 1]])

In [6]:
arr[4, 2:5]

array([4, 8, 5])

In [7]:
arr.sum(axis=1)

array([50, 30, 43, 50, 50, 49, 46, 25])

In [8]:
sumbyrow = arr.sum(axis=1)
min_index = sumbyrow.argmin()
(min_index, arr[min_index])

(7, array([3, 6, 1, 3, 0, 7, 3, 0, 1, 1]))

**3.** Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [9]:
x = np.array([1,3,6])
y = np.array([2,5,9])

np.sqrt(np.power(x - y,2).sum())

3.7416573867739413

**4.** Решить матричное уравнение** $A*X*B=-C$ - найти матрицу `X`, где

`A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, 

`B=[[3, -1], [2, 1]]`, 

`C=[[7, 21], [11, 8], [8, 4]]`.

In [10]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [11]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B) 
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [12]:
C = - (A @ X @ B)
C

array([[ 7., 21.],
       [11.,  8.],
       [ 8.,  4.]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

**1.** Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [13]:
data = np.loadtxt('minutes_n_ingredients.csv','int32',skiprows=1,delimiter=',')

In [14]:
data[0:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

**2.** Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [15]:
data_mean = np.mean(data[:,1:],axis=0) # data[:,1:] – обращаемся ко 2 столбцу, axis=0 - строки, axis=1 - столбцы
data_min = np.min(data[:,1:],axis=0)
data_max = np.max(data[:,1:],axis=0)
data_median = np.median(data[:,1:],axis=0)

print(f'Время использования рецепта:\n'
      f'Среднее значение = {data_mean[0]}, Минимум = {data_min[0]}, Максимум = {data_max[0]}, Медиана = {data_median[0]}.\n\n'
      f'Количество необходимых ингредиентов:\n'
      f'Среднее значение = {data_mean[1]}, Минимум = {data_min[1]}, Максимум = {data_max[1]}, Медиана = {data_median[1]}.')

Время использования рецепта:
Среднее значение = 21601.00169, Минимум = 0, Максимум = 2147483647, Медиана = 40.0.

Количество необходимых ингредиентов:
Среднее значение = 9.05528, Минимум = 1, Максимум = 39, Медиана = 9.0.


**3.** Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
data[np.random.choice(len(data), size=10, replace=False)]

array([[160779,     25,      6],
       [ 70188,      5,     14],
       [523799,      5,      4],
       [262015,     35,     15],
       [297600,     15,      6],
       [  3061,     22,     11],
       [111388,     40,     13],
       [ 42987,      0,      4],
       [ 96424,     50,     12],
       [197237,     60,     16]])

**4.** Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [17]:
data_less_then_5 = data[np.where(data[:,2] < 6)]
data_less_then_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

**5.** Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [18]:
part_ingr_less_mean = data[np.where(data[:,2] < np.mean(data[:,2]))].shape[0] / data.shape[0]
print(np.round(part_ingr_less_mean*100, 1),'%')

58.8 %


**6.** Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [19]:
#1 - с помощью numpy.clip()
data_q75 = copy.deepcopy(data)
data_q75[:,1] = np.clip(data[:,1], a_min=data[:,1].min(), a_max=np.quantile(data[:,1],0.75))
data_q75[:,1].max()

65

In [20]:
#2 - с помощью индексации массива
data_q75 = copy.deepcopy(data)
data_q75[:,1][data_q75[:,1] > np.quantile(data_q75[:,1],0.75)] = np.quantile(data[:,1],0.75)
data_q75[:,1].max() 

65

**7.** Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [21]:
data[np.where(data[:,1] == 0)].shape[0]

479

In [22]:
data[data[:,1] == 0] = 1
(data[:,1] == 0).sum()

0

**8.** Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [23]:
unique, quantity = np.unique(data[:,2], return_counts=True)
print(np.asarray((unique, quantity)).T)

[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


In [24]:
a = np.isin(np.arange(1,42), unique)
a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False, False])

In [25]:
np.where(a==False)

(array([35, 37, 39, 40], dtype=int64),)

In [26]:
not_in_interval = np.where(np.isin(np.arange(1,42), unique) == False)[0]
not_in_interval.tolist()

[35, 37, 39, 40]

**9.** Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [27]:
ingr_per_min = np.array(data[:,2]/data[:,1])
ingr_per_min

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [28]:
np.max(ingr_per_min), np.argmax(ingr_per_min)

(23.0, 77524)

**10.** Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [29]:
sorted_array = data[np.argsort(data[:,1])][-100 : ]
sorted_array

array([[    116645,      10095,          6],
       [    252450,      10100,          4],
       [     89339,      10105,          8],
       [    369728,      10110,          7],
       [    417539,      10110,          6],
       [    199925,      10140,          7],
       [    258854,      10320,         13],
       [     55411,      10320,          8],
       [     57721,      10440,         12],
       [    106876,      11520,          8],
       [    116809,      11521,          3],
       [    164029,      11550,         14],
       [    298229,      11565,          8],
       [     64793,      14405,          3],
       [    230796,      14420,          8],
       [    453387,      14420,          8],
       [    269245,      14425,          5],
       [    266032,      14430,          8],
       [     26995,      14450,         17],
       [    233539,      14460,         10],
       [    197469,      14460,         13],
       [    443929,      15880,          5],
       [  

In [30]:
np.mean(sorted_array[:,2])

6.61

**11.** Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [31]:
data_easy = np.append(copy.deepcopy(data), np.zeros((len(data),1), dtype=int) ,axis =1)
data_easy[:,3][np.where((data_easy[:,1]<21) & (data_easy[:,2]<6))[0]] = 1

data_easy

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [32]:
(data_easy[:,3] == 1).sum()

9943

**12.** Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [33]:
short_rec = data[np.where(data[:,1]<10)[0]]
mid_rec = data[np.where((data[:,1]>=10) & (data[:,1]<20))[0]]
long_rec = data[np.where(data[:,1]>=20)[0]]

In [34]:
min_size = np.min([short_rec.shape[0], mid_rec.shape[0], long_rec.shape[0]])
min_size

7588

In [40]:
all_recipes = np.array([short_rec[:min_size],mid_rec[:min_size],long_rec[:min_size]])
all_recipes

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [     1,      1,      1],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])

In [36]:
all_recipes[0][0][0]

67660

**13.** Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [37]:
chefs_job_price = np.array(data[:,1]*5)
ingr_price = np.array(data[:,2]*10)
total_price = chefs_job_price + ingr_price
total_price

array([460, 195, 110, ..., 475,  65, 840])

In [38]:
data_and_price = np.append(data,total_price.reshape((len(total_price),1)),axis=1)
data_and_price[0:10]

array([[127244,     60,     16,    460],
       [ 23891,     25,      7,    195],
       [ 94746,     10,      6,    110],
       [ 67660,      5,      6,     85],
       [157911,     60,     14,    440],
       [152828,     40,      7,    270],
       [ 33941,     18,      9,    180],
       [446597,     15,      5,    125],
       [366174,      7,      9,    125],
       [ 74205,     20,      7,    170]])

In [44]:
np.mean(data_and_price[:,3][:10])

216.0